#!/bin/bash
out=$(sudo docker ps -f name=$DOCKER_CONTAINER -f status=running -q)

if test -z "$out"; then
	existing=$(sudo docker ps -a -f name=$DOCKER_CONTAINER -q)

	if test -z "$existing"; then
		>&2 echo "No such container exists."
		exit 3
	else
		>&2 echo "Container not running."
		exit 2
	fi
else
	>&2 echo $out
	exit 0
fi
