#!/bin/bash
out=$(sudo docker ps -f name=$DOCKER_CONTAINER -f status=running -q)

if (( $? != 0 )); then
  exit 3
fi

if test -z "$out"; then
	existing=$(sudo docker ps -a -f name=$DOCKER_CONTAINER -q)

	if test -z "$existing"; then
		>&2 echo "No such container exists."
	else
		>&2 echo "Container not running."
	fi
  exit 2
else
  date=$(sudo docker inspect -f "{{.State.StartedAt}}" $DOCKER_CONTAINER | cut -d' ' -f1-3)
	>&2 echo "$out | uptime=$(($(date +%s)-$(date --date="$date" +%s)))s"
	exit 0
fi
